# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0003_auto_20170526_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
